In [1]:
# loading the Libaries 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from ucimlrepo import fetch_ucirepo

wine = fetch_ucirepo(id=186)

In [4]:
print(wine.keys())
print()
print(type(wine))
print()
print(wine.shape)

dict_keys(['data', 'metadata', 'variables'])

<class 'ucimlrepo.dotdict.dotdict'>

None

In [5]:
print(wine.data.keys())
print()
print(wine.metadata)
print()
print(wine.variables)

dict_keys(['ids', 'features', 'targets', 'original', 'headers'])

{'uci_id': 186, 'name': 'Wine Quality', 'repository_url': 'https://archive.ics.uci.edu/dataset/186/wine+quality', 'data_url': 'https://archive.ics.uci.edu/static/public/186/data.csv', 'abstract': 'Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).', 'area': 'Business', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 4898, 'num_features': 11, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['quality'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Wed Nov 15 2023', 'dataset_doi': '10.24432/C56S3T', 'creators': ['Paulo Cortez', 'A. Cerdeira', 'F. Almeida', 'T. Matos', 'J. Reis'], 'intro_paper': {'ID': 252, 'type': 'NATIVE', 'title': 'Modeling wine preferences by data mining from physicochemical properties', 'authors': 'P. Cortez, A. Cerdeira, Fernando Almeida, Telmo Matos, J. Reis', 'venue': 'Decision Support Systems', 'year': 2009, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/Modeling-wine-preferences-by-data-mining-from-Cortez-Cerdeira/bf15a0ccc14ac1deb5cea570c870389c16be019c', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine. For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].  Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).\n\nThese datasets can be viewed as classification or regression tasks.  The classes are ordered and not balanced (e.g. there are many more normal wines than excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent or poor wines. Also, we are not sure if all input variables are relevant. So it could be interesting to test feature selection methods.\n', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'For more information, read [Cortez et al., 2009].\r\nInput variables (based on physicochemical tests):\r\n   1 - fixed acidity\r\n   2 - volatile acidity\r\n   3 - citric acid\r\n   4 - residual sugar\r\n   5 - chlorides\r\n   6 - free sulfur dioxide\r\n   7 - total sulfur dioxide\r\n   8 - density\r\n   9 - pH\r\n   10 - sulphates\r\n   11 - alcohol\r\nOutput variable (based on sensory data): \r\n   12 - quality (score between 0 and 10)', 'citation': None}}

                    name     role         type demographic  \
0          fixed_acidity  Feature   Continuous        None
1       volatile_acidity  Feature   Continuous        None
2            citric_acid  Feature   Continuous        None
3         residual_sugar  Feature   Continuous        None
4              chlorides  Feature   Continuous        None
5    free_sulfur_dioxide  Feature   Continuous        None
6   total_sulfur_dioxide  Feature   Continuous        None
7                density  Feature   Continuous        None
8                     pH  Feature   Continuous        None
9              sulphates  Feature   Continuous        None
10               alcohol  Feature   Continuous        None
11               quality   Target      Integer        None
12                 color    Other  Categorical        None

               description units missing_values
0                      NaN  None             no
1                      NaN  None             no
2                      NaN  None             no
3                      NaN  None             no
4                      NaN  None             no
5                      NaN  None             no
6                      NaN  None             no
7                      NaN  None             no
8                      NaN  None             no
9                      NaN  None             no
10                     NaN  None             no
11  score between 0 and 10  None             no
12            red or white  None             no

In [9]:
df = pd.DataFrame(wine.data.features, columns=wine.data.headers)
df['quality'] = wine.data.targets

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  color                 0 non-null      float64
dtypes: float64(12), int64(1)
memory usage: 660.0 KB

In [11]:
df.drop('color', axis=1, inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 609.2 KB

In [13]:
print(df.duplicated().sum())
df[df.duplicated()]

1179

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4,7.4,0.700,0.00,1.90,0.076,11.0,34.0,0.99780,3.51,0.56,9.400000,5
11,7.5,0.500,0.36,6.10,0.071,17.0,102.0,0.99780,3.35,0.80,10.500000,5
27,7.9,0.430,0.21,1.60,0.106,10.0,37.0,0.99660,3.17,0.91,9.500000,5
40,7.3,0.450,0.36,5.90,0.074,12.0,87.0,0.99780,3.33,0.83,10.500000,5
65,7.2,0.725,0.05,4.65,0.086,4.0,11.0,0.99620,3.41,0.39,10.900000,5
...,...,...,...,...,...,...,...,...,...,...,...,...
6427,6.4,0.230,0.35,10.30,0.042,54.0,140.0,0.99670,3.23,0.47,9.200000,5
6449,7.0,0.360,0.35,2.50,0.048,67.0,161.0,0.99146,3.05,0.56,11.100000,6
6450,6.4,0.330,0.44,8.90,0.055,52.0,164.0,0.99488,3.10,0.48,9.600000,5
6455,7.1,0.230,0.39,13.70,0.058,26.0,172.0,0.99755,2.90,0.46,9.000000,6
6479,6.6,0.340,0.40,8.10,0.046,68.0,170.0,0.99494,3.15,0.50,9.533333,6

In [14]:
df.drop_duplicates(inplace=True)
df.info()

<class 'pandas.DataFrame'>
Index: 5318 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed_acidity         5318 non-null   float64
 1   volatile_acidity      5318 non-null   float64
 2   citric_acid           5318 non-null   float64
 3   residual_sugar        5318 non-null   float64
 4   chlorides             5318 non-null   float64
 5   free_sulfur_dioxide   5318 non-null   float64
 6   total_sulfur_dioxide  5318 non-null   float64
 7   density               5318 non-null   float64
 8   pH                    5318 non-null   float64
 9   sulphates             5318 non-null   float64
 10  alcohol               5318 non-null   float64
 11  quality               5318 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 540.1 KB

In [18]:
display(df.head(5))
print()
df.describe()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
count,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000,5318.000000
mean,7.215523,0.344171,0.318522,5.049605,0.056700,30.030463,114.107747,0.994536,3.224639,0.533402,10.549222,5.795600
std,1.319777,0.168264,0.147177,4.500645,0.036865,17.804365,56.783848,0.002966,0.160403,0.149753,1.185964,0.879715
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.240000,1.800000,0.038000,16.000000,74.000000,0.992200,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.300000,0.310000,2.700000,0.047000,28.000000,116.000000,0.994660,3.210000,0.510000,10.400000,6.000000
75%,7.700000,0.410000,0.400000,7.500000,0.066000,41.000000,153.750000,0.996770,3.330000,0.600000,11.400000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [20]:
num_cols = df.select_dtypes(include=[np.number]).columns.to_list()
cat_cols = df.select_dtypes(include=['object', 'str']).columns.to_list()

print('Numerical Category: ', num_cols)
print()
print('Categorical Category: ', cat_cols)

Numerical Category:  ['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

Categorical Category:  []

In [29]:
skewed = df[num_cols].skew()
skewed_cols = skewed[skewed > 1].index.to_list()
normal_cols = skewed[skewed < 1].index.to_list()
print(skewed)
print()
print(skewed_cols)
print()
print(normal_cols)

fixed_acidity           1.650055
volatile_acidity        1.504115
citric_acid             0.483817
residual_sugar          1.706027
chlorides               5.339077
free_sulfur_dioxide     1.363772
total_sulfur_dioxide    0.063667
density                 0.666033
pH                      0.390358
sulphates               1.809099
alcohol                 0.545866
quality                 0.147470
dtype: float64

['fixed_acidity', 'volatile_acidity', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'sulphates']

['citric_acid', 'total_sulfur_dioxide', 'density', 'pH', 'alcohol', 'quality']

In [25]:
out_cols = []
no_out_cols = []
out_sum = []

for col in num_cols:
    Q1= df[col].quantile(0.25)
    Q3= df[col].quantile(0.75)
    IQR= Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q1 + 1.5 * IQR

    outlier = df[(df[col] < lower) | (df[col] > upper)]
   
    if len(outlier) > 0:
        out_cols.append(col)
    else:
        no_out_cols.append(col)

    out_sum.append({
        'Column': col,
        'Outlier Count': len(outlier),
        'Total Row': len(df),
        'Outlier %': round(len(outlier)/len(df) * 100, 2)
    })

print("Columns with outliers:", out_cols)
print()
print("Columns without outliers:", no_out_cols)
print()

out_table = pd.DataFrame(out_sum)
display(out_table.sort_values(by='Outlier Count', ascending=False))

Columns with outliers: ['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'total_sulfur_dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

Columns without outliers: []

                  Column  Outlier Count  Total Row  Outlier %
11               quality           1038       5318      19.52
1       volatile_acidity            850       5318      15.98
3         residual_sugar            788       5318      14.82
4              chlorides            764       5318      14.37
0          fixed_acidity            740       5318      13.92
2            citric_acid            689       5318      12.96
9              sulphates            671       5318      12.62
5    free_sulfur_dioxide            545       5318      10.25
10               alcohol            523       5318       9.83
8                     pH            468       5318       8.80
6   total_sulfur_dioxide            420       5318       7.90
7                density            284       5318       5.34

In [27]:
df_corr = df[num_cols].corr()
df_corr['quality'].sort_values(ascending=False)

quality                 1.000000
alcohol                 0.469216
citric_acid             0.097926
free_sulfur_dioxide     0.054199
sulphates               0.042040
pH                      0.039789
total_sulfur_dioxide   -0.050183
residual_sugar         -0.056824
fixed_acidity          -0.080190
chlorides              -0.201960
volatile_acidity       -0.265354
density                -0.326301
Name: quality, dtype: float64

In [34]:
from sklearn.model_selection import train_test_split

X = df.drop('quality', axis=1)
y = df['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, random_state=42)

In [38]:
num_cols = X.select_dtypes(include=[np.number]).columns.to_list()

skewed = X[num_cols].skew()
skewed_cols = skewed[skewed > 1].index.to_list()
normal_cols = skewed[skewed <= 1].index.to_list()

print(skewed_cols)
print()
print(normal_cols)

['fixed_acidity', 'volatile_acidity', 'residual_sugar', 'chlorides', 'free_sulfur_dioxide', 'sulphates']

['citric_acid', 'total_sulfur_dioxide', 'density', 'pH', 'alcohol']

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.pipeline import make_pipeline

skewed_pipeline = make_pipeline(
    PowerTransformer(method='yeo-johnson'),
    StandardScaler()
)
normal_pipeline = make_pipeline(
    StandardScaler()
)

preprocessing = ColumnTransformer([
    ('skewed', skewed_pipeline, skewed_cols),
    ('normal', normal_pipeline, normal_cols)
])

In [40]:
# Train with different C 

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {
    'svr__kernel': ['linear', 'rbf'],
    'svr__C':[0.1, 0.5, 1, 10, 100],
    'svr__gamma': [0.1, 0.5, 1, 5, 10]
}

grid_rmse = GridSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_grid,
    cv=3,
    scoring='neg_root_mean_squared_error',
    n_jobs=1
)

grid_mae = GridSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_grid,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=1
)

grid_r2 = GridSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_grid,
    cv=3,
    scoring='r2',
    n_jobs=1
)

grid_rmse.fit(X_train, y_train)
grid_mae.fit(X_train, y_train)
grid_r2.fit(X_train, y_train)

print('RMSE Best Parameters: ', grid_rmse.best_params_)
print('RMSE Best Score: ', -grid_rmse.best_score_)
print() 
print('MAE Best Parameters: ', grid_mae.best_params_)
print('MAE Best Score: ', -grid_mae.best_score_)
print()
print('R2 Best Parameters: ', grid_r2.best_params_)
print('R2 Best Score: ', -grid_r2.best_score_)

RMSE Best Parameters:  {'svr__C': 0.5, 'svr__gamma': 0.1, 'svr__kernel': 'rbf'}
RMSE Best Score:  0.7089035755739377

MAE Best Parameters:  {'svr__C': 0.5, 'svr__gamma': 0.1, 'svr__kernel': 'rbf'}
MAE Best Score:  0.5369762850979909

R2 Best Parameters:  {'svr__C': 0.5, 'svr__gamma': 0.1, 'svr__kernel': 'rbf'}
R2 Best Score:  -0.3538273752576661

In [41]:
rmse_res = pd.DataFrame(grid_rmse.cv_results_)
mae_res = pd.DataFrame(grid_mae.cv_results_)
r2_res = pd.DataFrame(grid_r2.cv_results_)

cols = ['param_svr__kernel', 'param_svr__C', 'param_svr__gamma', 'mean_test_score', 'std_test_score', 'rank_test_score']

print('RMSE Results: ')
display(rmse_res[cols].sort_values('rank_test_score'))
print()

print('MAE Results: ')
display(mae_res[cols].sort_values('rank_test_score'))
print()

print('R2 Results: ')
display(r2_res[cols].sort_values('rank_test_score'))

RMSE Results:

,param_svr__kernel,param_svr__C,param_svr__gamma,mean_test_score,std_test_score,rank_test_score
11,rbf,0.5,0.1,-0.708904,0.014771,1
21,rbf,1.0,0.1,-0.710399,0.015290,2
1,rbf,0.1,0.1,-0.720026,0.013564,3
28,linear,1.0,10.0,-0.734861,0.008426,4
24,linear,1.0,1.0,-0.734861,0.008426,4
22,linear,1.0,0.5,-0.734861,0.008426,4
20,linear,1.0,0.1,-0.734861,0.008426,4
26,linear,1.0,5.0,-0.734861,0.008426,4
6,linear,0.1,5.0,-0.734865,0.008504,9
4,linear,0.1,1.0,-0.734865,0.008504,9
2,linear,0.1,0.5,-0.734865,0.008504,9
0,linear,0.1,0.1,-0.734865,0.008504,9
8,linear,0.1,10.0,-0.734865,0.008504,9
42,linear,100.0,0.5,-0.734875,0.008362,14
46,linear,100.0,5.0,-0.734875,0.008362,14
44,linear,100.0,1.0,-0.734875,0.008362,14
40,linear,100.0,0.1,-0.734875,0.008362,14
48,linear,100.0,10.0,-0.734875,0.008362,14
14,linear,0.5,1.0,-0.734881,0.008384,19
16,linear,0.5,5.0,-0.734881,0.008384,19
18,linear,0.5,10.0,-0.734881,0.008384,19
12,linear,0.5,0.5,-0.734881,0.008384,19
10,linear,0.5,0.1,-0.734881,0.008384,19
30,linear,10.0,0.1,-0.734890,0.008387,24
34,linear,10.0,1.0,-0.734890,0.008387,24
38,linear,10.0,10.0,-0.734890,0.008387,24
32,linear,10.0,0.5,-0.734890,0.008387,24
36,linear,10.0,5.0,-0.734890,0.008387,24
13,rbf,0.5,0.5,-0.739539,0.017529,29
23,rbf,1.0,0.5,-0.745361,0.016304,30
31,rbf,10.0,0.1,-0.753253,0.010238,31
25,rbf,1.0,1.0,-0.770172,0.019657,32
3,rbf,0.1,0.5,-0.772438,0.017716,33
35,rbf,10.0,1.0,-0.776387,0.017587,34
15,rbf,0.5,1.0,-0.777174,0.021589,35
45,rbf,100.0,1.0,-0.777271,0.016046,36
33,rbf,10.0,0.5,-0.803250,0.009028,37
43,rbf,100.0,0.5,-0.816317,0.009538,38
5,rbf,0.1,1.0,-0.832348,0.021417,39
47,rbf,100.0,5.0,-0.860721,0.024829,40
37,rbf,10.0,5.0,-0.860723,0.024832,41
27,rbf,1.0,5.0,-0.863436,0.025540,42
49,rbf,100.0,10.0,-0.871865,0.025282,43
39,rbf,10.0,10.0,-0.871865,0.025282,44
29,rbf,1.0,10.0,-0.873922,0.025988,45
17,rbf,0.5,5.0,-0.874255,0.027810,46
19,rbf,0.5,10.0,-0.881777,0.028122,47
7,rbf,0.1,5.0,-0.881778,0.023191,48
9,rbf,0.1,10.0,-0.883636,0.023197,49
41,rbf,100.0,0.1,-0.908955,0.004047,50

MAE Results:

,param_svr__kernel,param_svr__C,param_svr__gamma,mean_test_score,std_test_score,rank_test_score
11,rbf,0.5,0.1,-0.536976,0.007874,1
21,rbf,1.0,0.1,-0.539134,0.008017,2
1,rbf,0.1,0.1,-0.545581,0.006536,3
13,rbf,0.5,0.5,-0.558653,0.010534,4
6,linear,0.1,5.0,-0.562805,0.004419,5
8,linear,0.1,10.0,-0.562805,0.004419,5
2,linear,0.1,0.5,-0.562805,0.004419,5
0,linear,0.1,0.1,-0.562805,0.004419,5
4,linear,0.1,1.0,-0.562805,0.004419,5
14,linear,0.5,1.0,-0.562894,0.004227,10
10,linear,0.5,0.1,-0.562894,0.004227,10
12,linear,0.5,0.5,-0.562894,0.004227,10
16,linear,0.5,5.0,-0.562894,0.004227,10
18,linear,0.5,10.0,-0.562894,0.004227,10
20,linear,1.0,0.1,-0.562915,0.004221,15
22,linear,1.0,0.5,-0.562915,0.004221,15
26,linear,1.0,5.0,-0.562915,0.004221,15
28,linear,1.0,10.0,-0.562915,0.004221,15
24,linear,1.0,1.0,-0.562915,0.004221,15
48,linear,100.0,10.0,-0.562925,0.004176,20
40,linear,100.0,0.1,-0.562925,0.004176,20
42,linear,100.0,0.5,-0.562925,0.004176,20
46,linear,100.0,5.0,-0.562925,0.004176,20
44,linear,100.0,1.0,-0.562925,0.004176,20
34,linear,10.0,1.0,-0.562940,0.004171,25
38,linear,10.0,10.0,-0.562940,0.004171,25
32,linear,10.0,0.5,-0.562940,0.004171,25
30,linear,10.0,0.1,-0.562940,0.004171,25
36,linear,10.0,5.0,-0.562940,0.004171,25
23,rbf,1.0,0.5,-0.564854,0.009068,30
31,rbf,10.0,0.1,-0.576590,0.007281,31
3,rbf,0.1,0.5,-0.583165,0.007501,32
25,rbf,1.0,1.0,-0.589670,0.010741,33
35,rbf,10.0,1.0,-0.593158,0.008946,34
45,rbf,100.0,1.0,-0.593401,0.007510,35
15,rbf,0.5,1.0,-0.596485,0.012371,36
33,rbf,10.0,0.5,-0.613405,0.001145,37
43,rbf,100.0,0.5,-0.625624,0.006019,38
5,rbf,0.1,1.0,-0.632611,0.010356,39
7,rbf,0.1,5.0,-0.677225,0.011454,40
47,rbf,100.0,5.0,-0.678260,0.013105,41
37,rbf,10.0,5.0,-0.678267,0.013115,42
9,rbf,0.1,10.0,-0.678977,0.011594,43
41,rbf,100.0,0.1,-0.682749,0.001999,44
27,rbf,1.0,5.0,-0.685126,0.013503,45
49,rbf,100.0,10.0,-0.691172,0.014151,46
39,rbf,10.0,10.0,-0.691172,0.014152,47
29,rbf,1.0,10.0,-0.697803,0.014576,48
17,rbf,0.5,5.0,-0.705416,0.015438,49
19,rbf,0.5,10.0,-0.714776,0.016254,50

R2 Results:

,param_svr__kernel,param_svr__C,param_svr__gamma,mean_test_score,std_test_score,rank_test_score
11,rbf,0.5,0.1,0.353827,0.022788,1
21,rbf,1.0,0.1,0.350986,0.026407,2
1,rbf,0.1,0.1,0.333555,0.016004,3
28,linear,1.0,10.0,0.305431,0.024120,4
24,linear,1.0,1.0,0.305431,0.024120,4
22,linear,1.0,0.5,0.305431,0.024120,4
20,linear,1.0,0.1,0.305431,0.024120,4
26,linear,1.0,5.0,0.305431,0.024120,4
6,linear,0.1,5.0,0.305429,0.023997,9
4,linear,0.1,1.0,0.305429,0.023997,9
2,linear,0.1,0.5,0.305429,0.023997,9
0,linear,0.1,0.1,0.305429,0.023997,9
8,linear,0.1,10.0,0.305429,0.023997,9
42,linear,100.0,0.5,0.305400,0.024212,14
46,linear,100.0,5.0,0.305400,0.024212,14
44,linear,100.0,1.0,0.305400,0.024212,14
40,linear,100.0,0.1,0.305400,0.024212,14
48,linear,100.0,10.0,0.305400,0.024212,14
14,linear,0.5,1.0,0.305390,0.024178,19
16,linear,0.5,5.0,0.305390,0.024178,19
18,linear,0.5,10.0,0.305390,0.024178,19
12,linear,0.5,0.5,0.305390,0.024178,19
10,linear,0.5,0.1,0.305390,0.024178,19
30,linear,10.0,0.1,0.305374,0.024166,24
34,linear,10.0,1.0,0.305374,0.024166,24
38,linear,10.0,10.0,0.305374,0.024166,24
32,linear,10.0,0.5,0.305374,0.024166,24
36,linear,10.0,5.0,0.305374,0.024166,24
13,rbf,0.5,0.5,0.297094,0.016894,29
23,rbf,1.0,0.5,0.285766,0.022871,30
31,rbf,10.0,0.1,0.269973,0.032692,31
25,rbf,1.0,1.0,0.237846,0.012118,32
3,rbf,0.1,0.5,0.233305,0.008356,33
35,rbf,10.0,1.0,0.225343,0.014867,34
15,rbf,0.5,1.0,0.224084,0.006472,35
45,rbf,100.0,1.0,0.223510,0.014874,36
33,rbf,10.0,0.5,0.169883,0.035168,37
43,rbf,100.0,0.5,0.142266,0.044562,38
5,rbf,0.1,1.0,0.109926,0.004286,39
47,rbf,100.0,5.0,0.048380,0.001679,40
37,rbf,10.0,5.0,0.048375,0.001683,41
27,rbf,1.0,5.0,0.042403,0.003138,42
49,rbf,100.0,10.0,0.023586,0.002688,43
39,rbf,10.0,10.0,0.023585,0.002688,44
29,rbf,1.0,10.0,0.019011,0.003680,45
17,rbf,0.5,5.0,0.018367,0.007046,46
19,rbf,0.5,10.0,0.001407,0.007340,47
7,rbf,0.1,5.0,0.001103,0.003832,48
9,rbf,0.1,10.0,-0.003111,0.003929,49
41,rbf,100.0,0.1,-0.064297,0.067194,50

In [45]:
scoring = {
    "rmse": "neg_root_mean_squared_error",
    "mae": "neg_mean_absolute_error",
    "r2": "r2"
}

grid_multi = GridSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_grid,
    cv=3,
    scoring=scoring,
    refit="rmse",   # choose which metric decides the "best" model
    n_jobs=-1
)

grid_multi.fit(X_train, y_train)

results_multi = pd.DataFrame(grid_multi.cv_results_)
display(results_multi[['param_svr__kernel','param_svr__C','param_svr__gamma', 'mean_test_rmse','mean_test_mae','mean_test_r2']])

,param_svr__kernel,param_svr__C,param_svr__gamma,mean_test_rmse,mean_test_mae,mean_test_r2
0,linear,0.1,0.1,-0.734865,-0.562805,0.305429
1,rbf,0.1,0.1,-0.720026,-0.545581,0.333555
2,linear,0.1,0.5,-0.734865,-0.562805,0.305429
3,rbf,0.1,0.5,-0.772438,-0.583165,0.233305
4,linear,0.1,1.0,-0.734865,-0.562805,0.305429
5,rbf,0.1,1.0,-0.832348,-0.632611,0.109926
6,linear,0.1,5.0,-0.734865,-0.562805,0.305429
7,rbf,0.1,5.0,-0.881778,-0.677225,0.001103
8,linear,0.1,10.0,-0.734865,-0.562805,0.305429
9,rbf,0.1,10.0,-0.883636,-0.678977,-0.003111
10,linear,0.5,0.1,-0.734881,-0.562894,0.305390
11,rbf,0.5,0.1,-0.708904,-0.536976,0.353827
12,linear,0.5,0.5,-0.734881,-0.562894,0.305390
13,rbf,0.5,0.5,-0.739539,-0.558653,0.297094
14,linear,0.5,1.0,-0.734881,-0.562894,0.305390
15,rbf,0.5,1.0,-0.777174,-0.596485,0.224084
16,linear,0.5,5.0,-0.734881,-0.562894,0.305390
17,rbf,0.5,5.0,-0.874255,-0.705416,0.018367
18,linear,0.5,10.0,-0.734881,-0.562894,0.305390
19,rbf,0.5,10.0,-0.881777,-0.714776,0.001407
20,linear,1.0,0.1,-0.734861,-0.562915,0.305431
21,rbf,1.0,0.1,-0.710399,-0.539134,0.350986
22,linear,1.0,0.5,-0.734861,-0.562915,0.305431
23,rbf,1.0,0.5,-0.745361,-0.564854,0.285766
24,linear,1.0,1.0,-0.734861,-0.562915,0.305431
25,rbf,1.0,1.0,-0.770172,-0.589670,0.237846
26,linear,1.0,5.0,-0.734861,-0.562915,0.305431
27,rbf,1.0,5.0,-0.863436,-0.685126,0.042403
28,linear,1.0,10.0,-0.734861,-0.562915,0.305431
29,rbf,1.0,10.0,-0.873922,-0.697803,0.019011
30,linear,10.0,0.1,-0.734890,-0.562940,0.305374
31,rbf,10.0,0.1,-0.753253,-0.576590,0.269973
32,linear,10.0,0.5,-0.734890,-0.562940,0.305374
33,rbf,10.0,0.5,-0.803250,-0.613405,0.169883
34,linear,10.0,1.0,-0.734890,-0.562940,0.305374
35,rbf,10.0,1.0,-0.776387,-0.593158,0.225343
36,linear,10.0,5.0,-0.734890,-0.562940,0.305374
37,rbf,10.0,5.0,-0.860723,-0.678267,0.048375
38,linear,10.0,10.0,-0.734890,-0.562940,0.305374
39,rbf,10.0,10.0,-0.871865,-0.691172,0.023585
40,linear,100.0,0.1,-0.734875,-0.562925,0.305400
41,rbf,100.0,0.1,-0.908955,-0.682749,-0.064297
42,linear,100.0,0.5,-0.734875,-0.562925,0.305400
43,rbf,100.0,0.5,-0.816317,-0.625624,0.142266
44,linear,100.0,1.0,-0.734875,-0.562925,0.305400
45,rbf,100.0,1.0,-0.777271,-0.593401,0.223510
46,linear,100.0,5.0,-0.734875,-0.562925,0.305400
47,rbf,100.0,5.0,-0.860721,-0.678260,0.048380
48,linear,100.0,10.0,-0.734875,-0.562925,0.305400
49,rbf,100.0,10.0,-0.871865,-0.691172,0.023586

In [43]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVR

# Correct param distribution
param_dist = {
    'svr__kernel': ['linear', 'rbf'],   # <-- fixed
    'svr__C': [0.1, 0.5, 1.0, 10, 100],
    'svr__gamma': [0.1, 0.5, 1, 5, 10]
}

# RandomizedSearchCV for RMSE
random_rmse = RandomizedSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_distributions=param_dist,
    n_iter=25,
    cv=3,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    random_state=42
)

# RandomizedSearchCV for MAE
random_mae = RandomizedSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_distributions=param_dist,
    n_iter=25,
    cv=3,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42
)

# RandomizedSearchCV for R²
random_r2 = RandomizedSearchCV(
    make_pipeline(preprocessing, SVR()),
    param_distributions=param_dist,
    n_iter=25,
    cv=3,
    scoring='r2',
    n_jobs=-1,
    random_state=42
)

# Fit all
random_rmse.fit(X_train, y_train)
random_mae.fit(X_train, y_train)
random_r2.fit(X_train, y_train)

# Print results
print('Best params (RMSE): ', random_rmse.best_params_)
print('Best RMSE: ', -random_rmse.best_score_)
print()
print('Best params (MAE): ', random_mae.best_params_)
print('Best MAE:', -random_mae.best_score_)
print()
print('Best params (R²): ', random_r2.best_params_)
print('Best R²: ', random_r2.best_score_)

Best params (RMSE): {'svr__kernel': 'linear', 'svr__gamma': 5, 'svr__C': 1.0}
Best RMSE: 0.7348609705362766

Best params (MAE): {'svr__kernel': 'rbf', 'svr__gamma': 0.5, 'svr__C': 0.5}
Best MAE: 0.5586534112454257

Best params (R²): {'svr__kernel': 'linear', 'svr__gamma': 5, 'svr__C': 1.0}
Best R²: 0.3054306936252738

In [51]:
import pandas as pd

# Collect results into a list of dicts
results = [
    {
        'Metric': 'RMSE',   # removed leading space
        'Best Params': random_rmse.best_params_,
        'Best Score': -random_rmse.best_score_
    },
    {
        'Metric': 'MAE',
        'Best Params': random_mae.best_params_,
        'Best Score': -random_mae.best_score_
    },
    {
        'Metric': 'R²',
        'Best Params': random_r2.best_params_,
        'Best Score': random_r2.best_score_
    }
]

# Convert to DataFrame
results_df = pd.DataFrame(results)

display(results_df)

  Metric                                        Best Params  Best Score
0   RMSE  {'svr__kernel': 'linear', 'svr__gamma': 5, 'sv...    0.734861
1    MAE  {'svr__kernel': 'rbf', 'svr__gamma': 0.5, 'svr...    0.558653
2     R²  {'svr__kernel': 'linear', 'svr__gamma': 5, 'sv...    0.305431

In [50]:
# adding a Select from model 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import LinearSVR
from sklearn.linear_model import Lasso

skewed_pipeline = make_pipeline(
    PowerTransformer(method='yeo-johnson'),
    StandardScaler()
)
normal_pipeline = make_pipeline(
    StandardScaler()
)

preprocessing = ColumnTransformer([
    ('skewed', skewed_pipeline, skewed_cols),
    ('normal', normal_pipeline, normal_cols)
])


feature_selection =  SelectFromModel(
    Lasso(random_state=42),
    threshold='mean'
)

feature_selection2 =  SelectFromModel(
    RandomForestRegressor(random_state=42),
    threshold='median'
)

feature_selection3 = SelectFromModel(
    LinearSVR(random_state=42),
    threshold='mean'
)

model = make_pipeline(
    preprocessing, 
    feature_selection,
    SVR()
)

model2 = make_pipeline(
    preprocessing, 
    feature_selection2,
    SVR()
)

model3 = make_pipeline(
    preprocessing, 
    feature_selection3,
    SVR()
)

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid_lasso = {
    'selectfrommodel__estimator__alpha': [0.0001, 0.001, 0.01, 0.1],
    'selectfrommodel__threshold': ['mean', 'median'],   # fixed key + comma
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': [0.1, 0.5, 1, 10, 100],
    'svr__gamma': [0.1, 0.5, 1, 5, 10]
}

param_grid_random = {
    'selectfrommodel__estimator__n_estimators': [100, 200, 300, 400, 500],
    'selectfrommodel__estimator__max_depth': [None, 2, 5, 10],
    'selectfrommodel__threshold': ['mean', 'median'],
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': [0.1, 0.5, 1, 10, 100],
    'svr__gamma': [0.1, 0.5, 1, 5, 10]
}

param_grid_linear = {
    'selectfrommodel__estimator__C': [0.01, 0.1, 1],
    'selectfrommodel__estimator__epsilon': [0.01, 0.1],
    'selectfrommodel__threshold': ['mean', 'median'],
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': [0.1, 0.5, 1, 10, 100],
    'svr__gamma': [0.1, 0.5, 1, 5, 10]
}

scoring = {
    'rmse': 'neg_root_mean_squared_error',
    'mae': 'neg_mean_absolute_error',
    'r2': 'r2'
}

grid_lasso = GridSearchCV(
    model,
    param_grid_lasso,
    cv=3,
    scoring=scoring,
    refit='rmse',
    n_jobs=-1
)

grid_random = GridSearchCV(
    model2,
    param_grid_random,
    cv=3,
    scoring=scoring,
    refit='r2',
    n_jobs=-1
)

grid_linear = GridSearchCV(
    model3,
    param_grid_linear,
    cv=3,
    scoring=scoring,
    refit='mae',
    n_jobs=-1
)

grid_lasso.fit(X_train, y_train)
grid_random.fit(X_train, y_train)
grid_linear.fit(X_train, y_train)

print("Lasso Best params:", grid_lasso.best_params_)
print("Lasso Best RMSE:", -grid_lasso.best_score_)
print()
print("Random Best params:", grid_random.best_params_)
print("Random Best R²:", grid_random.best_score_)
print()
print("Linear Best params:", grid_linear.best_params_)
print("Linear Best MAE:", -grid_linear.best_score_)

In [ ]:
import pandas as pd

# Collect results into a list of dicts
results = [
    {
        "Selector": "Lasso",
        "Refit Metric": "RMSE",
        "Best Params": grid_lasso.best_params_,
        "Best Score": -grid_lasso.best_score_
    },
    {
        "Selector": "RandomForest",
        "Refit Metric": "R²",
        "Best Params": grid_random.best_params_,
        "Best Score": grid_random.best_score_
    },
    {
        "Selector": "LinearSVR",
        "Refit Metric": "MAE",
        "Best Params": grid_linear.best_params_,
        "Best Score": -grid_linear.best_score_
    }
]

# Convert to DataFrame
results_df = pd.DataFrame(results, columns=["Selector", "Refit Metric", "Best Params", "Best Score"])

# Display neatly
display(results_df)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.stats import uniform randint

param_dist_lasso = {
    'selectfrommodel__estimator__alpha': uniform(0.0001, 0.001, 0.01, 0.1),
    'selectfrommodel__threshold': ['mean', 'median'],   # fixed key + comma
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': uniform(0.1, 0.5, 1, 10, 100),
    'svr__gamma': uniform(0.1, 0.5, 1, 5, 10)
}

param_dist_random = {
    'selectfrommodel__estimator__n_estimators': randint(100, 200, 300, 400, 500),
    'selectfrommodel__estimator__max_depth': randint(None, 2, 5, 10),
    'selectfrommodel__threshold': ['mean', 'median'],
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': uniform(0.1, 0.5, 1, 10, 100,
    'svr__gamma': uniform(0.1, 0.5, 1, 5, 10)
}

param_dist_linear = {
    'selectfrommodel__estimator__C': uniform(0.01, 0.1, 1),
    'selectfrommodel__estimator__epsilon': uniform(0.01, 0.1),
    'selectfrommodel__threshold': ['mean', 'median'],
    'svr__kernel': ['linear', 'rbf'],
    'svr__C': uniform(0.1, 0.5, 1, 10, 100),
    'svr__gamma': uniform(0.1, 0.5, 1, 5, 10)
}

scoring = {
    'rmse': 'neg_root_mean_squared_error',
    'mae': 'neg_mean_absolute_error',
    'r2': 'r2'
}

dist_lasso = RandomizedSearchCV(
    model,
    param_distributions = param_dist_lasso,
    n_iter=25,
    cv=3,
    scoring=scoring,
    refit='rmse',
    n_jobs=-1,
    random_state=42 
)

dist_random = GridSearchCV(
    model2,
    param_distributions = param_dist_random,
    n_iter=25,
    cv=3,
    scoring=scoring,
    refit='r2',
    n_jobs=-1,
    random_state=42 
)

dist_linear = GridSearchCV(
    model3,
    param_distributions = param_dist_linear,
    n_iter=25,
    cv=3,
    scoring=scoring,
    refit='mae',
    n_jobs=-1,
    random_state=42   
)

dist_lasso.fit(X_train, y_train)
dist_random.fit(X_train, y_train)
dist_linear.fit(X_train, y_train)

print("Lasso Best params:", dist_lasso.best_params_)
print("Lasso Best RMSE:", -dist_lasso.best_score_)
print()
print("Random Best params:", dist_random.best_params_)
print("Random Best R²:", dist_random.best_score_)
print()
print("Linear Best params:", dist_linear.best_params_)
print("Linear Best MAE:", -dist_linear.best_score_)